api = "2"
core = "7.x"

projects[] = "ctools"
projects[] = "features"
projects[] = "field_sql_storage"
projects[] = "image"
projects[] = "node"
projects[] = "pushtape_core"
projects[] = "page_manager"
projects[] = "panelizer"
projects[] = "strongarm"
projects[] = "taxonomy"
projects[] = "text"
projects[] = "views"