<?php

/**
 * @file
 * Code for the Pushtape News feature.
 */

include_once('pushtape_news.features.inc');

/*
 * Implementation of hook_preprocess_page
 */
function pushtape_news_preprocess_page(&$vars, $hook) {
  drupal_add_feed('rss.xml', 'RSS');
}


/**
 * Implementation of hook_apps_app_info()
 */
function pushtape_news_apps_app_info() {
  return array(
    'demo content module' => 'pushtape_news_democontent',
    'configure form' => 'pushtape_news_configure_form', 
  );
}


/** 
 * Pushtape News App Configuration Form
 *
 * This form will be blank until we have specific settings to customize beyond
 * the demo content that the apps.module puts here for us. 
 */
function pushtape_news_configure_form($form, &$form_state) {
  $form = array();

   return $form;
}

/**
 * Implementation hook_panelizer_default_types_alter()
 */
function pushtape_news_panelizer_defaults_alter(&$defaults) {
  // Require the panels panelizer include from features since 
  // features doesn't support hook_panelizer_defaults() correctly.
  // See https://drupal.org/node/1427150 for more on that.
  require_once('pushtape_news.panelizer.inc');
  foreach(pushtape_news_panelizer_defaults() as $name => $default) {
    $defaults[$name] = $default;
  }
}
