api = 2
core = 7.x

projects[addthis][version] = 4.0-alpha1
projects[addthis][subdir] = contrib

projects[defaultcontent][subdir] = contrib

projects[uuid][subdir] = contrib

projects[entityreference][subdir] = contrib

projects[ctools][subdir] = contrib
projects[ctools][type] = module

projects[features][subdir] = contrib
projects[features][type] = module

projects[pathauto][subdir] = contrib
projects[pathauto][type] = module

projects[strongarm][type] = module
projects[strongarm][subdir] = contrib

projects[views][type] = module
projects[views][subdir] = contrib

projects[views_slideshow][type] = module
projects[views_slideshow][subdir] = contrib

projects[jquery_update][type] = module
projects[jquery_update][subdir] = contrib

libraries[jquery.cycle][download][type] = get
libraries[jquery.cycle][download][url] = "http://malsup.github.com/jquery.cycle.all.js"
libraries[jquery.cycle][directory_name] = jquery.cycle
libraries[jquery.cycle][type] = library
