<?php

/**
 * @file
 * Code for the Pushtape News feature.
 */

include_once('pushtape_news.features.inc');

/*
 * Implementation of hook_preprocess_page
 */
function pushtape_news_preprocess_page(&$vars, $hook) {
  drupal_add_feed('rss.xml', 'RSS');
}


/**
 * Implementation of hook_apps_app_info()
 */
function pushtape_news_apps_app_info() {
  return array(
    'demo content module' => 'pushtape_news_democontent',
    'configure form' => 'pushtape_news_configure_form', 
  );
}


/** 
 * Pushtape News App Configuration Form
 *
 * This form will be blank until we have specific settings to customize beyond
 * the demo content that the apps.module puts here for us. 
 */
function pushtape_news_configure_form($form, &$form_state) {
  $form = array();

   return $form;
}
